### ISSUE TITLE
ReferenceError: branchName is not defined;

### ISSUE THREAD

**Issue by FrankyBoy** [tc-radiate/tc-radiate#1] opened 2014-04-01 16:50 UTC
Hi!

I wanted to set this up today and ran into some strange error:
https://gist.github.com/FrankyBoy/4ee5e0c42b2cc66213b5

In the config I only changed the server and set the mainBranch to an empty string (because the buildStatusUrl didn't like any other value). From going through the code I have not the slightest issue whats going wrong :/

**Comment by mrbalihai** [comment] 2014-04-01 18:46
Hello Sir!

At a guess it looks like the error is relating to the binding for the 'branchName' reference on line 14 on Index.html. You could try changing it to have a null check there. 
If buildStatusUrl didn't work then perhaps this could be a version issue with Team City, we're running this with Team City 8.0.1 at the moment.
The Team City API maps directly onto JavasScript objects so a good way to diagnose issues with this is to hit the API URL directly and see what's there versus what's referenced in the HTML bindings.

I hope this helps.

**Comment by FrankyBoy** [comment] 2014-04-02 13:26
Found it, thx. Will have a look on the weekend how we can adapt this for our needs. For now commenting out the line did the trick :)

**Comment by ewilde** [comment] 2014-05-12 09:17
Yep I ran in to exactly this issue. We are on TeamCity 8.1.2 (build 29993).

**Comment by mrbalihai** [comment] 2014-05-12 10:00
The code makes quite a lot of assumptions about what the team city API returns and I'm looking into a couple of issues surrounding null data coming back in Team City 8.1.2. I've not had this specific 'branchName' issue myself though. A long shot but If you could provide a dump of the data that comes back from TeamCity when the issue is happening then that would help.

**Comment by FrankyBoy** [comment] 2014-05-12 10:14
Sure, just tell me the methods you need and I'll dump them into a gist :)

**Comment by mrbalihai** [comment] 2014-05-12 10:24
/guestAuth/app/rest/builds?locator=running:any,branch:branched:any,count:20

If you could tag that onto the end of your team city URL and gist me the response that would be awesome.

Thanks!

**Comment by ewilde** [comment] 2014-05-12 10:30
Should mention the VCS provider in teamcity we are using is TFS. Don't think TC has branch support for TFS. This might be the cause

**Comment by FrankyBoy** [comment] 2014-05-12 10:35
Here you go https://gist.github.com/FrankyBoy/b69083bc802313c33720

**Comment by mrbalihai** [comment] 2014-05-12 10:37
Indeed it sounds very much like that could be the problem. I'll have a look at making the branch name a bit more flexible.

**Comment by ewilde** [comment] 2014-05-12 11:02
Thanks, I made local changes to get it working on TFS. People at work love tc-radiate btw.

**Comment by mrbalihai** [comment] 2014-05-12 12:33
Ah excellent! I'm pleased to hear that :-)

**Comment by mrbalihai** [comment] 2014-05-12 12:33
@FrankyBoy Thanks for that!

**Comment by mrbalihai** [comment] 2014-05-12 12:41
I've just committed a change that will hopefully fix it if no branch name is present, it just displays the build number instead. I don't have a way of testing with the TFS provider easily so you'll have to let me know how you get on :-)

**Comment by ewilde** [comment] 2014-06-13 15:35
@RobBollons sorry for the delay. Fix works a charm. Only adjustment I had to make was in the `Settings.buildStatusUrl` property

``` bash
Settings.buildStatusUrl = Settings.proxy + Settings.teamCityUrl + '/guestAuth/app/rest/builds/running:any,canceled:any';
```

**Comment by mrbalihai** [comment] 2014-06-13 18:20
No worries. Good stuff. Cheers!

**Closed as completed by mrbalihai** 2014-06-13 18:20 UTC
Labels: bug
